[project]
name = "getignore3"
version = "3.0.0"
description = "Get gitignore files without bothering yourself"
authors = [
    { name = "ashkanfeyzollahi@gmail.com", email = "ashkanfeyzollahi@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["requests (>=2.32.4,<3.0.0)"]

[project.scripts]
getignore = "getignore:getignore"

[tool.poetry]
packages = [{ include = "getignore.py", from = "src" }]


[tool.poetry.group.dev.dependencies]
ruff = "^0.12.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
