[project]
name = "office-word-mcp-uvx-server"
version = "0.2.5"
description = "模型上下文协议（MCP）服务器，允许您在无需安装Microsoft Word 的情况下操作 Word 文件。使用您的AI代理创建、阅读和修改 Word 工作簿。"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp==2.10.6",
    "python-docx>=1.1.0"
]
[[project.authors]]
name = "fuyingjun"
email = "fuyingjun@example.com"

[project.urls]
Homepage = "https://github.com/your-username/office-word-mcp-uvx-server"
Repository = "https://github.com/your-username/office-word-mcp-uvx-server"
Issues = "https://github.com/your-username/office-word-mcp-uvx-server/issues"

[project.scripts]
word-mcp-server = "word_mcp.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/word_mcp"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""
