[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "konfigurator"
version = "0.2.1"
description = "A a simple python configuration management and object instantiation tool"
authors = [{ name="Maxim Dolgov", email="maxim.dolgov@hs-pforzheim.de" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ml_collections==1.1.0"
]
keywords = ["config"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
"Homepage" = "https://github.com/isealab/konfigurator"

[tool.setuptools.packages.find]
where = ["."]

[project.optional-dependencies]
dev = ["pre-commit==4.2.0", "build", "twine"]
test = ["pytest==8.4.1"]
