[project]
version = "1.0.0b6"
name = "ouroboros-gis"
authors = [{name = "Corbel", email = "dev@corbelspatial.com"}]
dynamic = []
requires-python = ">=3.10"
dependencies = [
    "fiona",
    "geoarrow-pyarrow",
    "geojson",
    "geopandas",
    "numpy",
    "pandas",
    "pyarrow",
    "pyogrio",
    "rasterio"
]
description = "Towards more pythonic use of GeoDatabases"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: OS Independent",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Intended Audience :: Information Technology",
    "Topic :: Scientific/Engineering :: GIS"

]

[project.urls]
homepage = "https://pypi.org/project/ouroboros-gis/"
documentation = "https://ouroboros-gis.readthedocs.io/en/latest/"
repository = "https://github.com/corbel-spatial/ouroboros"
issues = "https://github.com/corbel-spatial/ouroboros/issues"
changelog = "https://github.com/corbel-spatial/ouroboros/blob/main/CHANGELOG.md"

[dependency-groups]
docs = ["jupyter", "matplotlib", "myst-parser", "nbsphinx", "notebook",
        "pydata-sphinx-theme", "sphinx", "sphinx-copybutton", "sphinx-rtd-theme"]
lint = ["black"]
test = ["pytest", "coverage", "pytest-xdist"]
dev = [
    { include-group = "docs" },
    { include-group = "lint" },
    { include-group = "test" }
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

# dev install steps
# python -m build
# python -m pip install -e . --group dev
#
# build docs
# .\docs\make html; .\docs\make html; start .\docs\_build\html\index.html
#
# generate coverage
# coverage run -m pytest .\tests\tests.py; coverage html; start .\htmlcov\index.html
# coverage run -m pytest .\tests\tests.py; coverage json -o .\docs\pytest_coverage.json  --pretty-print