[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fixed-width-int"
version = "0.1.0a2"
description = "A robust implementation of fixed-width integers in Python that precisely emulates C-style behavior."
readme = "README.md"
requires-python = ">=2"
license = "MIT"
authors = [
  { name="Jifeng Wu", email="jifengwu2k@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "six",
    "typing; python_version < '3.5'"
]

[project.urls]
"Homepage" = "https://github.com/jifengwu2k/fixed-width-int"
"Bug Tracker" = "https://github.com/jifengwu2k/fixed-width-int/issues"