[project]
name = "infra-new"
version = "0.1.0.dev3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp[speedups]>=3.12.14",
    "asyncer>=0.0.8",
    "python-dotenv>=1.1.1",
    "typer>=0.16.0",
]

[dependency-groups]
dev = ["pytest>=8.4.1"]

[project.scripts]
infra = "infra_cli:app"
