[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jupyter_remote_kernel"
version = "1.3.1"
description = "Remote Jupyter Kernel Launcher with SSH port forwarding"
authors = [{ name = "Leo", email = "leoustc@icloud.com" }]
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
remote_kernel = "remote_kernel.cli:main"


