[project]
name = "necbol"
version = "3.2.3"
license = "MIT"

authors = [
  { name="G1OJS", email="g1ojs@yahoo.com" },
]
description = "A plain language Python wrapper for NEC"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.0",
    "matplotlib"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Telecommunications Industry",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
]

keywords = ["nec", "antenna", "wire editor", "3D", "electromagnetics", "ham radio", "radio", "optimisation"]

[project.urls]
Homepage = "https://github.com/G1OJS/NECBOL"
Issues = "https://github.com/G1OJS/NECBOL/issues"

[tool.setuptools]
packages = ["necbol"]
license-files = ["LICENSE"]
