[build-system]
requires = ["setuptools>=69", "wheel", "setuptools_scm[toml]>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "EANOMAD"
version = "0.1.1.post3"                # or use setuptoolsâ€‘scm
description = "Evolutionary optimizer with NOMAD local search"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
authors = [{name = "Miles Churchland", email = "mileschurchand@gmail.com"}]
requires-python = ">=3.9"
dependencies = [
  "numpy>=1.23",
  "tqdm>=4.66",
  "pynomadbbo>=4",
]
optional-dependencies.ray = ["ray>=2.10"]   # `pip install pure-nomad[ray]`

[project.urls]
Source = "https://github.com/greenfire0/EANOMAD"