[project]
name = "cwyodmodules"
authors = [
  { name="Patrik", email="patrikhartl@gmail.com" },
]
version = '0.9.50'
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.10,<3.12"
classifiers = [
    "Operating System :: OS Independent",
]
dependencies = [
    "openai==1.95.1",
    "flask==3.1.1",
    "azure-mgmt-cognitiveservices (>=13.6.0,<14.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "chardet==5.2.0",
    "azure-ai-formrecognizer (>=3.3.3,<4.0.0)",
    "tiktoken (>=0.8.0,<1.0.0)",
    "azure-functions==1.23.0",
    "python-docx (>=1.1.2,<2.0.0)",
    "azure-ai-contentsafety (>=1.0.0,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "requests>=2.32.3,<3.0.0",
    "azure-cognitiveservices-speech (>=1.42.0,<2.0.0)",
    "psycopg==3.2.4",
    "psycopg2-binary==2.9.10",
    "psycopg[binary]",
    "beautifulsoup4==4.13.3",
    "semantic-kernel==1.3.0",
    "pydantic==2.7.4",
    "pandas>=2.2.3",
    "langchain==0.3.26",
    "azpaddypy>=0.9.20",
]

[tool.uv]
dev-dependencies = [
    "pytest==8.4.1",
    "pytest-asyncio==1.0.0",
    "anyio==4.9.0"
]


[tool.setuptools.package-data]
'*' = ['*.json','*.txt']
