[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "EzQt_App"
version = "4.0.3.post1"
description = "Lightweight framework based on PySide6 to quickly build modern desktop applications, with integrated resource, theme, and reusable component management."
readme = "README.md"
requires-python = ">=3.9,<3.13"
license = { text = "MIT" }
authors = [{ name = "Florian Salort", email = "floriansalort@gmail.com" }]
keywords = ["application", "framework"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Office/Business",
]

dependencies = [
    "PySide6==6.9.1",
    "PyYaml==6.0.2",
    "ruamel.yaml==0.18.6",
    "colorama==0.4.6",
    "requests==2.32.3",
    "click>=8.0.0",
    "ezqt-widgets>=2.0.0",
    "langdetect"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0", 
    "pytest-qt>=4.0.0",      # Pour les tests Qt
    "pytest-mock>=3.10.0",   # Pour le mocking
    "pytest-xdist>=3.0.0",   # Pour les tests parallÃ¨les
    "flake8>=5.0.0",
    "black>=22.0.0",
    "mypy>=1.0.0"
]

[project.scripts]
ezqt = "ezqt_app.cli.main:cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["ezqt_app", "ezqt_app.*"]

[tool.setuptools.package-data]
ezqt_app = [
    "resources/*",
    "resources/fonts/*",
    "resources/themes/*",
    "resources/images/*",
    "resources/icons/*",
    "resources/translations/*",
    "app.yaml",
]
