[project]
name = "pg-db-operation-mcp-server"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lishuang", email = "lishuang@microconnect.com" }
]
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "dashscope>=1.24.0",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.2",
    "psycopg2>=2.9.10",
    "pymysql>=1.1.1",
]

[project.scripts]
pg-db-operation-mcp-server = "pg_db_operation_mcp_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
