[project]
name = "ptyrodactyl"
version = "2025.07.15"
description = "Ptychography through differentiable programming in JAX"
authors = [{name = "Debangshu Mukherjee", email = "mukherjeed@ornl.gov"}]
license = {file = "LICENSE.md"}
maintainers = [{name = "Debangshu Mukherjee", email = "mukherjeed@ornl.gov"}]
keywords = [
    "electron microscopy", 
    "optical microscopy",
    "4D-STEM",
    "JAX",
    "ptychography",
    "differentiable programming",
]
readme = "README.md"
requires-python = ">=3.11, <3.13"
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Typing :: Typed",
    "Topic :: Scientific/Engineering :: Image Processing",
]
dependencies = [
    "numpy>=1.13.0",
    "scipy >= 1.0.0",
    "matplotlib >= 2.2.0",
    "matplotlib-scalebar >= 0.5.0",
    "tqdm >= 4.66.0",
    "jaxtyping>=0.2.21",
    "chex >= 0.1.85",
    "optax >= 0.1.8",
    "pytest >= 8.0.0",
    "beartype>=0.19.0",
    "black[jupyter]>=25.1.0",
    "jax[cuda12]>=0.4.30 ; sys_platform == 'linux'",
    "jax>=0.4.30 ; sys_platform == 'win64'",
    "isort>=6.0.1",
]

[tool.setuptools]
include-package-data = true
license-files = []

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
    "myst-parser>=4.0.1",
    "nbsphinx>=0.9.6",
    "pydata-sphinx-theme>=0.16.1",
    "sphinx>=8.1.3",
    "sphinx-rtd-theme>=3.0.2",
    "sphinxcontrib-napoleon>=0.7",
    "twine>=6.1.0",
]

[project.optional-dependencies]
docs = [
    "ipykernel>=6.29.5",
    "myst-parser>=4.0.1",
    "nbsphinx>=0.9.6",
    "pydata-sphinx-theme>=0.16.1",
    "sphinx>=8.1.3",
    "sphinx-rtd-theme>=3.0.2",
    "sphinxcontrib-napoleon>=0.7",
]

[project.urls]
Homepage = "https://github.com/debangshu-mukherjee/ptyrodactyl"


[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "ptyrodactyl"
namespace = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.coverage.run]
source = ["ptyrodactyl"]
omit = ["*/tests/*", "*/site-packages/*"]
