[project]
name = "mcex-mcp-server"
version = "2.1.0"
description = "滴灌通客服助手"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "dashscope>=1.23.5",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
    "requests~=2.32.4",
    "mcp~=1.9.4",
    "pydantic~=2.11.7"
]

[project.scripts]
mcex-mcp-server = "mcex_mcp_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"