[build-system]
requires = ["setuptools>=65.0.0", "wheel"]

[project]
name = "hypha-artifact"
version = "0.0.12"
readme = "README.md"
authors = [
  { name = "Hugo Dettner KÃ¤llander", email = "hugokallander@gmail.com"}
]
description = "Hypha Artifact package, used with Hypha."
requires-python = ">=3.11"
dependencies = [
  "requests>=2.28.0",
  "httpx",
  "python-dotenv>=0.21.0",
  "hypha_rpc>=0.20.54",
]
license = "MIT"
license-files = ["LICENSE"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["hypha_artifact*"]
exclude = ["tests*"]