[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "tldw"
version = "1.0.4"
authors = [
  { name="David Zirinsky", email="dzirinsky@gmail.com" },
]
description = "A Python package to summarize YouTube videos using the OpenAI API."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.31.0",
    "youtube-transcript-api>=1.0.3",
    "pyfiglet>=0.8.post1",
    "termcolor>=2.4.0",
]

[project.urls]
"Homepage"    = "https://github.com/DavidZirinsky/tl-dw"
"Bug Tracker" = "https://github.com/DavidZirinsky/tl-dw/issues"
"Source"      = "https://github.com/DavidZirinsky/tl-dw"
