[project]
    name = "debug-dojo"
    description = "Debbugging dojo for Python developers"
    authors = [
        { name = "bwrob", email = "bartosz.marcin.wroblewski@gmail.com" },
    ]
    requires-python = ">=3.10"
    dependencies = [
        "pudb>=2020.1",
        "rich>=11.0.0",
        "typer>=0.15.0",
    ]
    license = 'MIT'
    license-files = ['LICENSE']
    keywords = [
        "debugging",
        "inspection",
        "pudb",
        "rich",
        "tools",
        "traceback",
    ]
    classifiers = [
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Software Development :: Debuggers",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ]
    version = "0.3.0"
    dynamic = ['readme']

    [project.urls]
        Homepage      = "https://github.com/bwrob/debug-dojo"
        Documentation = "https://github.com/bwrob/debug-dojo/blob/main/README.md"
        Source        = "https://github.com/bwrob/debug-dojo/tree/main/src/debug_dojo"
        Changelog     = "https://github.com/bwrob/debug-dojo/blob/main/HISTORY.md"

    [project.scripts]
        # This defines your command-line script!
        # It points to the 'main' function in your 'cli' module.
        "dojo" = "debug_dojo._cli:main"

[dependency-groups]
    dev = ["basedpyright>=1.31.0", "ruff>=0.12.4"]

[build-system]
    requires = [
        "hatch-fancy-pypi-readme>=25.1.0",
        "hatchling",
    ]
    build-backend = "hatchling.build"


[tool.hatch.version]
    path = "src/debug_dojo/version.py"

[tool.hatch.metadata]
    allow-direct-references = true

    [tool.hatch.metadata.hooks.fancy-pypi-readme]
        content-type = 'text/markdown'
        # construct the PyPI readme from README.md and HISTORY.md
        fragments = [
            { path = 'README.md' },
            { text = "\n\n## Changelog\n\n" },
            { path = 'HISTORY.md' },
        ]

[tool.basedpyright]
    typeCheckingMode = "all"
    pythonVersion    = "3.10"
    strict           = ["src/debug_dojo/*"]
    ignore           = ["examples"]
