[project]
name = "psplines"
version = "0.1.2"
description = "Implementation of PSplines in Python"
readme = "README.md"
authors = [
    { name = "Grayson Bellamy", email = "graysontbellamy@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "pymc",
    "matplotlib",
    "pytensor",
    "arviz",
]

[project.scripts]
psplines = "psplines:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
