[project]
name = "notionary"
version = "0.2.17"
description = "Python library for programmatic Notion workspace management - databases, pages, and content with advanced Markdown support"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Mathis Arends", email = "mathisarends27@gmail.com" }
]
license = { text = "MIT" }
dependencies = [
    "httpx>=0.28.0",
    "python-dotenv>=1.1.0",
    "pydantic>=2.11.4",
    "posthog (>=6.3.1,<7.0.0)",
    "aiofiles (>=24.1.0,<25.0.0)",
]

[project.urls]
Homepage = "https://github.com/mathisarends/notionary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.15"
black = "^25.1.0"

