[project]
name = "spclone"
version = "0.1.13"
description = "A lightweight alternative to 'git clone' for installing Python packages directly from GitHub."
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }    
authors = [
    { name = "Sermet Pekin", email = "Sermet.Pekin@gmail.com" }
]

dependencies = [
    "requests>=2.32.4"
]

[project.scripts]
spclone = "spclone.cli:clone"
spinstall = "spclone.cli:main"

[project.urls]
Repository = "https://github.com/SermetPekin/spclone"
Homepage = "https://github.com/SermetPekin/spclone"
Documentation = "https://github.com/SermetPekin/spclone"
Issues = "https://github.com/SermetPekin/spclone/issues"
Changelog = "https://github.com/SermetPekin/spclone/releases"

[tool.pdm.dev-dependencies]
dev = [
    "black>=25.1.0",
    "flake8>=7.3.0",
    "pytest>=8.4.1",
    "ruff>=0.12.5"
]

