[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mdis-sec"
version = "0.1.0"
authors = [
  { name="MemeCoder", email="memecoder17@gmail.com" },
]
license = "Apache-2.0"
license-files = ["LICENSE"]
description = "MDIS - Malware Detection and Identification System."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/memecoder12345678/mdis"
"Bug Tracker" = "https://github.com/memecoder12345678/mdis/issues"
