[project]
name = "kina"
version = "1.4.4"
description = "A simple tool to create ephemeral AKS Clusters"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.22.0",
    "azure-mgmt-authorization>=4.0.0",
    "azure-mgmt-compute>=34.1.0",
    "azure-mgmt-containerregistry>=14.0.0",
    "azure-mgmt-containerservice>=35.0.0",
    "azure-mgmt-network>=28.1.0",
    "azure-mgmt-resource>=23.3.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "typer>=0.15.3",
]

[dependency-groups]
dev = ["ruff>=0.11.9"]

[project.scripts]
kina = "kina:app"

[tool.uv]
package = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203",
    "D213",
    "D407",
    "FBT001",
    "FBT002",
    "W605",
    "TRY003",
    "EM101",
    "FIX002",
    "PLR0913",
]
