[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "terrakio-api"
version = "0.4.6"
authors = [
    {name = "Yupeng Chao", email = "yupeng@haizea.com.au"},
]
description = "A client library for Terrakio's WCS API service"
readme = "README.md"
requires-python = ">3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "terrakio-core==0.4.6",
    "requests>=2.25.0",
    "pyyaml>=5.1",
    "xarray>=2023.1.0",
    "netcdf4>=1.6.0",
    "pandas>=1.5.0",
    "numpy>=1.22.0",
    "scipy>=1.8.0",
    "shapely>=2.0.0",
]

[project.optional-dependencies]
ml = [
    "terrakio-core[ml]==0.4.6",
]

[project.urls]
"Homepage" = "https://github.com/HaizeaAnalytics/terrakio-python-api"
"Bug Tracker" = "https://github.com/HaizeaAnalytics/terrakio-python-api/issues" 