[tool.ruff]
line-length = 128

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eiogram"
version = "1.7.2"
authors = [
    {name = "Erfan", email = "erfjab@gmail.com"},
]
description = "A Python library for"
readme = "README.md"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.8.0",
    "pydantic>=2.11.4",
]

[project.urls]
Homepage = "https://github.com/erfjab/eiogram"
