[project]
name = "traceplot"
version = "1.0.4"
description = "Static map generator with points plots."
readme = "README.md"
authors = [
    { name = "Colin Dugeai", email = "colin.dugeai@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "pyproj>=3.7.1",
    "requests>=2.32.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://github.com/cdugeai/traceplot"
Issues = "https://github.com/cdugeai/traceplot/issues"

[dependency-groups]
dev = [
    "coverage>=7.9.2",
    "mypy>=1.17.0",
    "pytest>=8.4.1",
    "ruff>=0.12.4",
    "types-requests>=2.32.4.20250611",
]
