[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "brushable_widget"
version = "0.1.8"
dependencies = [
    "anywidget",
    "marimo>=0.11.17",
    "svg-py>=1.5.0",
]
readme = "README.md"

# Dependency groups (recognized by `uv`). For more details, visit:
# https://peps.python.org/pep-0735/
[dependency-groups]
dev = ["watchfiles"]
