[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xmodules"
version = "1.0.2"
description = "XModules: view-once media-ni Saved Messages ga saqlaydi."
readme = "README.md"
license = "MIT"
authors = [
  { name = "AlijonovUz" }
]
requires-python = ">=3.8"
dependencies = [
  "telethon>=1.40.0"
]

[project.urls]
Homepage = "https://github.com/AlijonovUz/"
