[project]
name = "NL2SQLEvaluator"
version = "0.1.7"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langgraph>=0.4.0",
    "loguru>=0.7.3",
    "numpy>=1.9.0",
    "pydantic>=2.11.7",
    "pymysql>=1.1.1",
    "sqlalchemy>=2.0.41",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

[project.scripts]
NL2SQLEvaluator = "NL2SQLEvaluator:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
