[project]
name = "snipd_export_parser"
version = "0.1.1"
description = "A tool to parse Snipd export Markdown files into individual chapter files."
authors = [
    {name = "菜就多練練",email = "im@bgzo.cc"}
]
license = {text = "AGPL-3.0"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyyaml (>=6.0.2,<6.1.0)",
    "click (>=8.1.8,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
#package-mode= false

# 可选，命令行入口
[tool.poetry.scripts]
cli="snipd_export_parser:cli"
snipd="snipd_export_parser:main"
